
## spring组件配置，相关配置
spring:
  datasource:
    # jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    # useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    url: jdbc:mysql://127.0.0.1:3306/test?ssl=true&useSSL=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒(SELECT 1 FROM DUAL)
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    logSlowSql: true
    #spring.datasource.poolPreparedStatements=true
    #spring.datasource.maxOpenPreparedStatements=20


