
server:
  ## 端口号
  port: 8766
  context-path: /
  ## session超时时间，单位秒(session-timeout: 60)
  session:
    timeout: 1800


## spring组件配置
## 默认使用主配置文件，配置了这个会优先读取里面的属性覆盖主配置文件的属性
spring:
  ## 关于spring cache可以查看spring官方的文档
  cache:
    type: redis
    ## 缓存名称
    #cache-names: redis-cache
    ehcache:
      config: classpath:config/ehcache.xml
    #redis:
      ## 是否缓存null值
      #cache-null-values: false
      ## 缓存过期时间
      #time-to-live: 60s
      ## 是否使用key前缀
      #use-key-prefix: true
      ## 使用key前缀
      #key-prefix: cache_key_prefix_
  ## Redis配置参数，缓存配置-Caching-Redis(RedisProperties)
  redis:
    ## redis哨兵设置
    ## Redis服务器master的名字
    ## spring.redis.sentinel.master=master8026
    ## redis-sentinel的配置地址和端口
    ## spring.redis.sentinel.nodes=10.189.80.25:26379,10.189.80.26:26379,10.189.80.27:26378

    ## SpringBoot2.0默认采用Lettuce客户端来连接Redis服务端的
    ## 默认是不使用连接池的，只有配置 redis.lettuce.pool下的属性的时候才可以使用到redis连接池
    cluster:
      max-redirects: 3
      ## ${redis.host.cluster} 10.55.5.7:6382,10.55.5.7:6384,10.55.5.7:6383
      nodes: 10.55.5.6:6379,10.55.5.7:6382,10.55.5.6:6381,10.55.5.6:6380,10.55.5.7:6384,10.55.5.7:6383
      timeout: 5000
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址，192.168.1.134,192.168.1.130
    host: 10.55.5.6
    ## Redis服务器连接密码（默认为空）${redis.password}
    password: ''

    ## 可能无jedis(boot-1.5.16.RELEASE)
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        # 单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException  1000ms
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0

    #lettuce:
      ## 关闭超时时间
      #shutdown-timeout: 100
      #pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #max-active: 8
        ## 连接池中的最大空闲连接
        #max-idle: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #max-wait: 30
        ## 连接池中的最小空闲连接
        #min-idle: 0
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000




#Pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

