
server:
  ## 服务端口号
  port: 8085

## spring组件配置
## 默认使用主配置文件，配置了这个会优先读取里面的属性覆盖主配置文件的属性
spring:
  datasource:
    # jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    # useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    url: jdbc:mysql://127.0.0.1:3306/test?ssl=true&useSSL=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒(SELECT 1 FROM DUAL)
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    logSlowSql: true
    #spring.datasource.poolPreparedStatements=true
    #spring.datasource.maxOpenPreparedStatements=20


#公共的mapper配置
mapper:
  mappers: org.palm.spring.cloud.base.BaseMapper
  not-empty: false
  identity: mysql

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
## 该配置节点为独立的节点，这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径(META-INF  MYBATIS_SysUserXmlMapper)
  mapper-locations: classpath:mybatis/mapper/*.xml
  #注意：扫描对应实体类的路径,mybatis包的扫描，还有就是映射文件设置 mybatis tk插件的使用
  type-aliases-package: org.palm.spring.cloud.service.user.repository.entity
#  not-empty: false
#  identity: MYSQL
   #mappers 多个接口时逗号隔开
#   mappers: tk.mybatis.mapper.common.Mapper

  #该配置只在配置字段名正常的entity中起作用
  #在properties中添加以下配置，在执行查询后，可以将数据库的NN_NN格式字段，在java结果集对象中自动转换成驼峰命名参数，使用BaseResultMap不会自动驼峰转换的
  configuration:
    map-underscore-to-camel-case: false
    #default-fetch-size: 100
    #default-statement-timeout: 3000

